apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: reasonable-store
  labels:
    app: backend
    tier: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
        - name: backend
          image: therajatsingh/backend:v2  # ← replace with your image
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASS
            - name: STORE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: STORE_EMAIL
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: reasonable-store
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
